# Generated by Django 4.1.5 on 2023-01-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
