# Generated by Django 4.1.5 on 2023-01-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_alter_item_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='title_price_constraint',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('title', 'price'), name='title_price_constraint', violation_error_message='Поля меняй уебок'),
        ),
    ]
