# Generated by Django 4.1.5 on 2023-01-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_alter_style_description_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.URLField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=80),
        ),
    ]
