# Generated by Django 4.1.5 on 2023-01-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0005_alter_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
