# Generated by Django 4.1.5 on 2023-01-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0008_user_subscriptions_alter_item_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='sex',
            new_name='gender',
        ),
    ]
