# Generated by Django 4.1.5 on 2023-01-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0010_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='url',
            new_name='ref_url',
        ),
    ]
