# Generated by Django 4.1.5 on 2023-01-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0011_rename_url_item_ref_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
