# Generated by Django 4.1.5 on 2023-01-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0013_alter_item_author_alter_style_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
